import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { dbConfig } from "@/utils/dbConfig";
import { ClerkProvider, SignedIn } from "@clerk/nextjs";
import Header from "./Header";
import { GlobalContext } from "./globalContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await dbConfig();
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <div>
            <SignedIn>
              <Header />
            </SignedIn>

            <div>
              <GlobalContext>{children}</GlobalContext>
            </div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
